import Head from 'next/head'
import axios from 'axios'
import { useEffect, useState } from 'react'

export default function Home() {
  const [pokemons, setPokemons] = useState({})

  useEffect(() => {
    async function getPokemons() {
      axios
        .get('https://pokeapi.co/api/v2/pokemon?limit=100')
        .then(response => setPokemons(response.data.results))
        .catch(err => {
          console.error('ops! ocorreu um erro' + err)
        })
    }

    getPokemons()
  }, [])

  console.log(pokemons)
  return (
    <div>
      <Head>
        <title>Pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen flex justify-center ">
        <div>
          <div className="text-3xl font-mono">
            Which pokemon do you want to know?
          </div>
          <div>
            <select className="w-full bg-gray-400/50 rounded-md p-2">
              {pokemons?.map(pokemon => {
                return <option>{pokemon.name}</option>
              })}
            </select>
            {/* {pokemons.id} */}
          </div>
        </div>
      </main>

      <footer className=""></footer>
    </div>
  )
}
