import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Stocks</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen flex justify-center items-center">
        <div>
          <div className="text-3xl font-mono">
            Which stock do you want to know?
          </div>
          <div>
            <select className="w-full bg-gray-400/50 rounded-md p-2">
              <option>oi</option>
            </select>
          </div>
        </div>
      </main>

      <footer className=""></footer>
    </div>
  )
}
